### PR TITLE
Use word-wrap package for wrapping

### PR DESCRIPTION
**Pull request by jtdaugherty**

### CODE REVIEW

**Comment by callum-oakley** [comment]
Thanks for this. I've opened an issue: https://github.com/jtdaugherty/word-wrap/issues/2

Causes files to not have any of their blank lines displayed:

screen shot 2017-08-01 at 22 41 14

Haven't had a chance to take a look at the implementation to see what's going on, but happy to do so. Will submit a PR if I get a chance.

**Comment by callum-oakley** [comment]
Just had a chance to take another look at this. Thanks for the prompt fix! There's one other behaviour difference preventing me from immediately merging this. My custom word wrapping implementation preserves the indentation level of a line when it wraps it – while `wrapText` just puts all wrapped lines at the beginning of a new line. Here's an example

screen shot 2017-08-03 at 18 53 11

and here's the same example with my existing implementation

screen shot 2017-08-03 at 18 55 57

**Comment by jtdaugherty** [comment]
Yeah, the behavior you desire is not called "wrapping" - it's called "filling." I could make my package support that, too, but it entails adding a new function because this is not always the desired behavior.

**Comment by jtdaugherty** [comment]
(I'm willing to add such a function, though.)

**Comment by jtdaugherty** [comment]
`word-wrap` version `0.2` now provides control over how indentation is handled.

**Comment by jtdaugherty** [comment]
I just pushed a patch that uses the new `word-wrap` release.

**Comment by callum-oakley** [comment]
Thanks for this! I'm still not 100% happy with the default behaviour, but I'm pretty sure this is my last complaint...

Since we are wrapping lines to fit them in a fixed width, we need *single words* which are longer than the target width to be broken up. For example, note the URL towards the bottom of the `README.md` file in this repository.

on `master`

screen shot 2017-08-04 at 22 16 36

with `wrapText`

screen shot 2017-08-04 at 22 18 30

In the latter the end of the URL is cut off.

I've opened an issue: https://github.com/jtdaugherty/word-wrap/issues/3

**Comment by jtdaugherty** [comment]
Thanks for the suggestion!

**Comment by callum-oakley** [comment]
Looks like this only breaks words if there aren't any other really long words on the line. e.g. wrapping the following

    reallyLongWord
    short
    
    reallyLongWord short
    
    short reallyLongWord

to 10 characters gives us

    reallyLong
    Word
    short
    
    reallyLongWord short
    
    short reallyLongWord

but I would expect

    reallyLong
    Word
    short
    
    reallyLong
    Word short
    
    short
    reallyLong
    Word

(Which is what you get with the wrapping algorithm that `vim` uses)

**Comment by jtdaugherty** [comment]
Fixed in `0.3.1`.

**Comment by jtdaugherty** [comment]
> I'm still not 100% happy with the default behaviour, but I'm pretty sure this is my last complaint...

For what it's worth, trying `word-wrap` with your project is *fantastic* because it's uncovering these issues. I wrote it as a simple thing to start with, but I'm glad we're trying it out here because this will make it more useful!

**Comment by callum-oakley** [comment]
Good to hear this is useful feedback and not just annoying! I feel like we're getting pretty close now. The latest version fixes my previous issue, but now words are broken even if they *aren't* too long. For example:

screen shot 2017-08-06 at 17 37 25

rather than what I would expect:

screen shot 2017-08-06 at 17 38 09

**Comment by jtdaugherty** [comment]
Fixed in `0.3.3`.

**Comment by callum-oakley** [comment]
`0.3.3` introduced a funky bug! I made a PR with a fix: https://github.com/jtdaugherty/word-wrap/pull/5

**Comment by callum-oakley** [comment]
Okay! I'm pretty happy with this now. Thanks for accommodating my use case in `word-wrap`!

**Comment by jtdaugherty** [comment]
You're welcome. I'm glad we could make it work, because I just couldn't bear to see that you had implemented word-wrapping yourself -- lots of people have done it, and as we well know, it's hard to get right and hard to do generically enough to work for everyone. I made `word-wrap` to save other people time. :)

**Comment by callum-oakley** [comment]
Absolutely! 🙂  I'll certainly keep an eye on `word-wrap` going forward.

**Pull request merged**
